export const REPOSITORY_LIST_REQUEST = 'REPOSITORY_LIST_REQUEST';
export const REPOSITORY_LIST_SUCCESS = 'REPOSITORY_LIST_SUCCESS';
export const REPOSITORY_LIST_FAIL = 'REPOSITORY_LIST_FAIL';

export const REPOSITORY_DETAILS_REQUEST = 'REPOSITORY_DETAILS_REQUEST';
export const REPOSITORY_DETAILS_SUCCESS = 'REPOSITORY_DETAILS_SUCCESS';
export const REPOSITORY_DETAILS_FAIL = 'REPOSITORY_DETAILS_FAIL';